'\" t
.\"     Title: signal-cli
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/28/2021
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "SIGNAL\-CLI" "1" "08/28/2021" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
signal-cli \- A commandline and dbus interface for the Signal messenger
.SH "SYNOPSIS"
.sp
\fBsignal\-cli\fR [\-\-config CONFIG] [\-h | \-v | \-u USERNAME | \-\-dbus | \-\-dbus\-system] command [command\-options]
.SH "DESCRIPTION"
.sp
signal\-cli is a commandline interface for libsignal\-service\-java\&. It supports registering, verifying, sending and receiving messages\&. For registering you need a phone number where you can receive SMS or incoming calls\&. signal\-cli was primarily developed to be used on servers to notify admins of important events\&. For this use\-case, it has a dbus interface, that can be used to send messages from any programming language that has dbus bindings\&.
.sp
For some functionality the Signal protocol requires that all messages have been received from the server\&. The receive command should be regularly executed\&. In daemon mode messages are continuously received\&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help message and quit\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Print the version and quit\&.
.RE
.PP
\fB\-\-verbose\fR
.RS 4
Raise log level and include lib signal logs\&.
.RE
.PP
\fB\-\-config\fR CONFIG
.RS 4
Set the path, where to store the config\&. Make sure you have full read/write access to the given directory\&. (Default:
$XDG_DATA_HOME/signal\-cli
($HOME/\&.local/share/signal\-cli))
.RE
.PP
\fB\-u\fR USERNAME, \fB\-\-username\fR USERNAME
.RS 4
Specify your phone number, that will be your identifier\&. The phone number must include the country calling code, i\&.e\&. the number must start with a "+" sign\&.
.RE
.sp
This flag must not be given for the link command\&. It is optional for the daemon command\&. For all other commands it is only optional if there is exactly one local user in the config directory\&.
.PP
\fB\-\-dbus\fR
.RS 4
Make request via user dbus\&.
.RE
.PP
\fB\-\-dbus\-system\fR
.RS 4
Make request via system dbus\&.
.RE
.PP
\fB\-o\fR OUTPUT\-MODE, \fB\-\-output\fR OUTPUT\-MODE
.RS 4
Specify if you want commands to output in either "plain\-text" mode or in "json"\&. Defaults to "plain\-text"
.RE
.PP
\fB\-\-trust\-new\-identities\fR TRUST\-MODE
.RS 4
Choose when to trust new identities:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
on\-first\-use
(default): Trust the first seen identity key from new users, changed keys must be verified manually
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
always: Trust any new identity key without verification
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
never: Don\(cqt trust any unknown identity key, every key must be verified manually
.RE
.RE
.SH "COMMANDS"
.SS "register"
.sp
Register a phone number with SMS or voice verification\&. Use the verify command to complete the verification\&.
.PP
\fB\-v\fR, \fB\-\-voice\fR
.RS 4
The verification should be done over voice, not SMS\&.
.RE
.PP
\fB\-\-captcha\fR
.RS 4
The captcha token, required if registration failed with a captcha required error\&. To get the token, go to
https://signalcaptchas\&.org/registration/generate\&.html
Check the developer tools for a redirect starting with signalcaptcha:// Everything after signalcaptcha:// is the captcha token\&.
.RE
.SS "verify"
.sp
Verify the number using the code received via SMS or voice\&.
.PP
VERIFICATIONCODE
.RS 4
The verification code\&.
.RE
.PP
\fB\-p\fR PIN, \fB\-\-pin\fR PIN
.RS 4
The registration lock PIN, that was set by the user\&. Only required if a PIN was set\&.
.RE
.SS "unregister"
.sp
Disable push support for this device, i\&.e\&. this device won\(cqt receive any more messages\&. If this is the primary device, other users can\(cqt send messages to this number anymore\&. Use "updateAccount" to undo this\&. To remove a linked device, use "removeDevice" from the primary device\&.
.PP
\fB\-\-delete\-account\fR
.RS 4
Delete account completely from server\&. Cannot be undone without loss\&. You will have to be readded to each group\&.
.RE
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBCaution\fR
.ps -1
.br
.sp
Only delete your account if you won\(cqt use this number again!
.sp .5v
.RE
.SS "updateAccount"
.sp
Update the account attributes on the signal server\&. Can fix problems with receiving messages\&.
.SS "setPin"
.sp
Set a registration lock pin, to prevent others from registering this number\&.
.PP
REGISTRATION_LOCK_PIN
.RS 4
The registration lock PIN, that will be required for new registrations (resets after 7 days of inactivity)
.RE
.SS "removePin"
.sp
Remove the registration lock pin\&.
.SS "link"
.sp
Link to an existing device, instead of registering a new number\&. This shows a "tsdevice:/\&..." URI\&. If you want to connect to another signal\-cli instance, you can just use this URI\&. If you want to link to an Android/iOS device, create a QR code with the URI (e\&.g\&. with qrencode) and scan that in the Signal app\&.
.PP
\fB\-n\fR NAME, \fB\-\-name\fR NAME
.RS 4
Optionally specify a name to describe this new device\&. By default "cli" will be used\&.
.RE
.SS "addDevice"
.sp
Link another device to this device\&. Only works if this is the primary device\&.
.PP
\fB\-\-uri\fR URI
.RS 4
Specify the uri contained in the QR code shown by the new device\&. You will need the full uri enclosed in quotation marks, such as "tsdevice:/?uuid=\&...\&.\&."
.RE
.SS "listDevices"
.sp
Show a list of linked devices\&.
.SS "removeDevice"
.sp
Remove a linked device\&. Only works if this is the primary device\&.
.PP
\fB\-d\fR DEVICE_ID, \fB\-\-device\-id\fR DEVICE_ID
.RS 4
Specify the device you want to remove\&. Use listDevices to see the deviceIds\&.
.RE
.SS "getUserStatus"
.sp
Uses a list of phone numbers to determine the statuses of those users\&. Shows if they are registered on the Signal Servers or not\&. In json mode this is outputted as a list of objects\&.
.PP
[NUMBER [NUMBER \&...]]
.RS 4
One or more numbers to check\&.
.RE
.SS "send"
.sp
Send a message to another user or group\&.
.PP
RECIPIENT
.RS 4
Specify the recipients\(cq phone number\&.
.RE
.PP
\fB\-g\fR GROUP, \fB\-\-group\-id\fR GROUP
.RS 4
Specify the recipient group ID in base64 encoding\&.
.RE
.PP
\fB\-m\fR MESSAGE, \fB\-\-message\fR MESSAGE
.RS 4
Specify the message, if missing, standard input is used\&.
.RE
.PP
\fB\-a\fR [ATTACHMENT [ATTACHMENT \&...]], \fB\-\-attachment\fR [ATTACHMENT [ATTACHMENT \&...]]
.RS 4
Add one or more files as attachment\&.
.RE
.PP
\fB\-\-note\-to\-self\fR
.RS 4
Send the message to self without notification\&.
.RE
.PP
\fB\-e\fR, \fB\-\-end\-session\fR
.RS 4
Clear session state and send end session message\&.
.RE
.SS "sendReaction"
.sp
Send reaction to a previously received or sent message\&.
.PP
RECIPIENT
.RS 4
Specify the recipients\(cq phone number\&.
.RE
.PP
\fB\-g\fR GROUP, \fB\-\-group\-id\fR GROUP
.RS 4
Specify the recipient group ID in base64 encoding\&.
.RE
.PP
\fB\-e\fR EMOJI, \fB\-\-emoji\fR EMOJI
.RS 4
Specify the emoji, should be a single unicode grapheme cluster\&.
.RE
.PP
\fB\-a\fR NUMBER, \fB\-\-target\-author\fR NUMBER
.RS 4
Specify the number of the author of the message to which to react\&.
.RE
.PP
\fB\-t\fR TIMESTAMP, \fB\-\-target\-timestamp\fR TIMESTAMP
.RS 4
Specify the timestamp of the message to which to react\&.
.RE
.PP
\fB\-r\fR, \fB\-\-remove\fR
.RS 4
Remove a reaction\&.
.RE
.SS "sendReceipt"
.sp
Send a read or viewed receipt to a previously received message\&.
.PP
RECIPIENT
.RS 4
Specify the sender\(cqs phone number\&.
.RE
.PP
\fB\-t\fR TIMESTAMP, \fB\-\-target\-timestamp\fR TIMESTAMP
.RS 4
Specify the timestamp of the message to which to react\&.
.RE
.PP
\fB\-\-type\fR TYPE
.RS 4
Specify the receipt type, either
read
(the default) or
viewed\&.
.RE
.SS "sendTyping"
.sp
Send typing message to trigger a typing indicator for the recipient\&. Indicator will be shown for 15seconds unless a typing STOP message is sent first\&.
.PP
RECIPIENT
.RS 4
Specify the recipients\(cq phone number\&.
.RE
.PP
\fB\-g\fR GROUP, \fB\-\-group\-id\fR GROUP
.RS 4
Specify the recipient group ID in base64 encoding\&.
.RE
.PP
\fB\-s\fR, \fB\-\-stop\fR
.RS 4
Send a typing STOP message\&.
.RE
.SS "remoteDelete"
.sp
Remotely delete a previously sent message\&.
.PP
RECIPIENT
.RS 4
Specify the recipients\(cq phone number\&.
.RE
.PP
\fB\-g\fR GROUP, \fB\-\-group\-id\fR GROUP
.RS 4
Specify the recipient group ID in base64 encoding\&.
.RE
.PP
\fB\-t\fR TIMESTAMP, \fB\-\-target\-timestamp\fR TIMESTAMP
.RS 4
Specify the timestamp of the message to delete\&.
.RE
.SS "receive"
.sp
Query the server for new messages\&. New messages are printed on standard output and attachments are downloaded to the config directory\&. In json mode this is outputted as one json object per line\&.
.PP
\fB\-t\fR TIMEOUT, \fB\-\-timeout\fR TIMEOUT
.RS 4
Number of seconds to wait for new messages (negative values disable timeout)\&. Default is 5 seconds\&.
.RE
.PP
\fB\-\-ignore\-attachments\fR
.RS 4
Don\(cqt download attachments of received messages\&.
.RE
.SS "joinGroup"
.sp
Join a group via an invitation link\&.
.PP
\fB\-\-uri\fR
.RS 4
The invitation link URI (starts with
https://signal\&.group/#)
.RE
.SS "updateGroup"
.sp
Create or update a group\&. If the user is a pending member, this command will accept the group invitation\&.
.PP
\fB\-g\fR GROUP, \fB\-\-group\-id\fR GROUP
.RS 4
Specify the recipient group ID in base64 encoding\&. If not specified, a new group with a new random ID is generated\&.
.RE
.PP
\fB\-n\fR NAME, \fB\-\-name\fR NAME
.RS 4
Specify the new group name\&.
.RE
.PP
\fB\-d\fR DESCRIPTION, \fB\-\-description\fR DESCRIPTION
.RS 4
Specify the new group description\&.
.RE
.PP
\fB\-a\fR AVATAR, \fB\-\-avatar\fR AVATAR
.RS 4
Specify a new group avatar image file\&.
.RE
.PP
\fB\-m\fR [MEMBER [MEMBER \&...]], \fB\-\-member\fR [MEMBER [MEMBER \&...]]
.RS 4
Specify one or more members to add to the group\&.
.RE
.PP
\fB\-r\fR [MEMBER [MEMBER \&...]], \fB\-\-remove\-member\fR [MEMBER [MEMBER \&...]]
.RS 4
Specify one or more members to remove from the group
.RE
.PP
\fB\-\-admin\fR [MEMBER [MEMBER \&...]]
.RS 4
Specify one or more members to make a group admin
.RE
.PP
\fB\-\-remove\-admin\fR [MEMBER [MEMBER \&...]]
.RS 4
Specify one or more members to remove group admin privileges
.RE
.PP
\fB\-\-reset\-link\fR
.RS 4
Reset group link and create new link password
.RE
.PP
\fB\-\-link\fR LINK_STATE
.RS 4
Set group link state:
enabled,
enabled\-with\-approval,
disabled
.RE
.PP
\fB\-\-set\-permission\-add\-member\fR PERMISSION
.RS 4
Set permission to add new group members:
every\-member,
only\-admins
.RE
.PP
\fB\-\-set\-permission\-edit\-details\fR PERMISSION
.RS 4
Set permission to edit group details:
every\-member,
only\-admins
.RE
.PP
\fB\-\-set\-permission\-send\-messages\fR PERMISSION
.RS 4
Set permission to send messages in group:
every\-member,
only\-admins
Groups where only admins can send messages are also called announcement groups
.RE
.PP
\fB\-e\fR EXPIRATION_SECONDS, \fB\-\-expiration\fR EXPIRATION_SECONDS
.RS 4
Set expiration time of messages (seconds)\&. To disable expiration set expiration time to 0\&.
.RE
.SS "quitGroup"
.sp
Send a quit group message to all group members and remove self from member list\&. If the user is a pending member, this command will decline the group invitation\&.
.PP
\fB\-g\fR GROUP, \fB\-\-group\-id\fR GROUP
.RS 4
Specify the recipient group ID in base64 encoding\&.
.RE
.PP
\fB\-\-delete\fR
.RS 4
Delete local group data completely after quitting group\&.
.RE
.SS "listGroups"
.sp
Show a list of known groups and related information\&. In json mode this is outputted as an list of objects and is always in detailed mode\&.
.PP
\fB\-d\fR, \fB\-\-detailed\fR
.RS 4
Include the list of members of each group and the group invite link\&.
.RE
.SS "listContacts"
.sp
Show a list of known contacts with names\&.
.SS "listIdentities"
.sp
List all known identity keys and their trust status, fingerprint and safety number\&.
.PP
\fB\-n\fR NUMBER, \fB\-\-number\fR NUMBER
.RS 4
Only show identity keys for the given phone number\&.
.RE
.SS "trust"
.sp
Set the trust level of a given number\&. The first time a key for a number is seen, it is trusted by default (TOFU)\&. If the key changes, the new key must be trusted manually\&.
.PP
number
.RS 4
Specify the phone number, for which to set the trust\&.
.RE
.PP
\fB\-a\fR, \fB\-\-trust\-all\-known\-keys\fR
.RS 4
Trust all known keys of this user, only use this for testing\&.
.RE
.PP
\fB\-v\fR VERIFIED_SAFETY_NUMBER, \fB\-\-verified\-safety\-number\fR VERIFIED_SAFETY_NUMBER
.RS 4
Specify the safety number of the key, only use this option if you have verified the safety number\&.
.RE
.SS "updateProfile"
.sp
Update the profile information shown to message recipients\&. The profile is stored encrypted on the Signal servers\&. The decryption key is sent with every outgoing messages to contacts and included in every group\&.
.PP
\fB\-\-given\-name\fR NAME, \fB\-\-name\fR NAME
.RS 4
New (given) name\&.
.RE
.PP
\fB\-\-family\-name\fR FAMILY_NAME
.RS 4
New family name\&.
.RE
.PP
\fB\-\-about\fR ABOUT_TEXT
.RS 4
New profile status text\&.
.RE
.PP
\fB\-\-about\-emoji\fR EMOJI
.RS 4
New profile status emoji\&.
.RE
.PP
\fB\-\-avatar\fR AVATAR_FILE
.RS 4
Path to the new avatar image file\&.
.RE
.PP
\fB\-\-remove\-avatar\fR
.RS 4
Remove the avatar
.RE
.SS "updateContact"
.sp
Update the info associated to a number on our contact list\&. This change is only local but can be synchronized to other devices by using sendContacts (see below)\&. If the contact doesn\(cqt exist yet, it will be added\&.
.PP
NUMBER
.RS 4
Specify the contact phone number\&.
.RE
.PP
\fB\-n\fR, \fB\-\-name\fR
.RS 4
Specify the new name for this contact\&.
.RE
.PP
\fB\-e\fR, \fB\-\-expiration\fR EXPIRATION_SECONDS
.RS 4
Set expiration time of messages (seconds)\&. To disable expiration set expiration time to 0\&.
.RE
.SS "block"
.sp
Block the given contacts or groups (no messages will be received)\&. This change is only local but can be synchronized to other devices by using sendContacts (see below)\&.
.PP
[CONTACT [CONTACT \&...]]
.RS 4
Specify the phone numbers of contacts that should be blocked\&.
.RE
.PP
\fB\-g\fR [GROUP [GROUP \&...]], \fB\-\-group\-id\fR [GROUP [GROUP \&...]]
.RS 4
Specify the group IDs that should be blocked in base64 encoding\&.
.RE
.SS "unblock"
.sp
Unblock the given contacts or groups (messages will be received again)\&. This change is only local but can be synchronized to other devices by using sendContacts (see below)\&.
.PP
[CONTACT [CONTACT \&...]]
.RS 4
Specify the phone numbers of contacts that should be unblocked\&.
.RE
.PP
\fB\-g\fR [GROUP [GROUP \&...]], \fB\-\-group\-id\fR [GROUP [GROUP \&...]]
.RS 4
Specify the group IDs that should be unblocked in base64 encoding\&.
.RE
.SS "sendContacts"
.sp
Send a synchronization message with the local contacts list to all linked devices\&. This command should only be used if this is the primary device\&.
.SS "sendSyncRequest"
.sp
Send a synchronization request message to the primary device (for group, contacts, \&...)\&. The primary device will respond with synchronization messages with full contact and group lists\&.
.SS "uploadStickerPack"
.sp
Upload a new sticker pack, consisting of a manifest file and the sticker images\&. Images must conform to the following specification: (see https://support\&.signal\&.org/hc/en\-us/articles/360031836512\-Stickers#sticker_reqs ) \- Static stickers in PNG or WebP format \- Animated stickers in APNG format, \- Maximum file size for a sticker file is 300KiB \- Image resolution of 512 x 512 px
.sp
The required manifest\&.json has the following format:
.sp
.if n \{\
.RS 4
.\}
.nf
{
  "title": "<STICKER_PACK_TITLE>",
  "author": "<STICKER_PACK_AUTHOR>",
  "cover": { // Optional cover, by default the first sticker is used as cover
    "file": "<name of image file, mandatory>",
    "contentType": "<optional>",
    "emoji": "<optional>"
  },
  "stickers": [
    {
      "file": "<name of image file, mandatory>",
      "contentType": "<optional>",
      "emoji": "<optional>"
    }
    \&.\&.\&.
  ]
}
.fi
.if n \{\
.RE
.\}
.PP
PATH
.RS 4
The path of the manifest\&.json or a zip file containing the sticker pack you wish to upload\&.
.RE
.SS "daemon"
.sp
signal\-cli can run in daemon mode and provides an experimental dbus interface\&. If no \-u username is given, all local users will be exported as separate dbus objects under the same bus name\&.
.PP
\fB\-\-system\fR
.RS 4
Use DBus system bus instead of user bus\&.
.RE
.PP
\fB\-\-ignore\-attachments\fR
.RS 4
Don\(cqt download attachments of received messages\&.
.RE
.SH "EXAMPLES"
.PP
Register a number (with SMS verification)
.RS 4
signal\-cli \-u USERNAME register
.RE
.PP
Verify the number using the code received via SMS or voice
.RS 4
signal\-cli \-u USERNAME verify CODE
.RE
.PP
Send a message to one or more recipients
.RS 4
signal\-cli \-u USERNAME send \-m "This is a message" [RECIPIENT [RECIPIENT \&...]] [\-a [ATTACHMENT [ATTACHMENT \&...]]]
.RE
.PP
Pipe the message content from another process
.RS 4
uname \-a | signal\-cli \-u USERNAME send [RECIPIENT [RECIPIENT \&...]]
.RE
.PP
Create a group
.RS 4
signal\-cli \-u USERNAME updateGroup \-n "Group name" \-m [MEMBER [MEMBER \&...]]
.RE
.PP
Add member to a group
.RS 4
signal\-cli \-u USERNAME updateGroup \-g GROUP_ID \-m "NEW_MEMBER"
.RE
.PP
Accept a group invitation
.RS 4
signal\-cli \-u USERNAME updateGroup \-g GROUP_ID
.RE
.PP
Leave a group
.RS 4
signal\-cli \-u USERNAME quitGroup \-g GROUP_ID
.RE
.PP
Send a message to a group
.RS 4
signal\-cli \-u USERNAME send \-m "This is a message" \-g GROUP_ID
.RE
.PP
Trust new key, after having verified it
.RS 4
signal\-cli \-u USERNAME trust \-v SAFETY_NUMBER NUMBER
.RE
.PP
Trust new key, without having verified it\&. Only use this if you don\(cqt care about security
.RS 4
signal\-cli \-u USERNAME trust \-a NUMBER
.RE
.SH "EXIT CODES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR: Error is probably caused and fixable by the user
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR: Some unexpected error
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB3\fR: Server or IO error
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB4\fR: Sending failed due to untrusted key
.RE
.SH "FILES"
.sp
The password and cryptographic keys are created when registering and stored in the current users home directory, the directory can be changed with \fB\-\-config\fR:
.sp
$XDG_DATA_HOME/signal\-cli/ ($HOME/\&.local/share/signal\-cli/)
.SH "AUTHORS"
.sp
Maintained by AsamK <asamk@gmx\&.de>, who is assisted by other open source contributors\&. For more information about signal\-cli development, see https://github\&.com/AsamK/signal\-cli\&.
